### ISSUE TITLE
Maybe some thing wrong with the script "demo_single.py"

### ISSUE THREAD

**Issue by yingzhao27** [tpoisonooo/llama.onnx#11]
Hello, thank you for your nice code. I was wondering there may be a minor bug in this “demo_single.py" that needs to be fixed, this is, in line 211, 
`input_ids = np.concatenate(
                [input_ids, next_token.reshape((1, 1))], axis=1)`
should be:
`next_token = np.concatenate(
                [input_ids, next_token.reshape((1, 1))], axis=1)`
https://github.com/tpoisonooo/llama.onnx/blob/36a293a38250e859ba10ed5310b7aff237c05fb6/demo-single.py#LL211C13-L211C13

**Comment by tpoisonooo** [comment]
Let me explain more.

Suppose that you asked "hello" and LLaMa replied "hello_everyone".

This code would loop until `FINISH_TOKEN`.

## First Iteration
```bash
next_token = input_id = "hello"
cache = None
..
# after `self.decode("hello")`
next_token = '_'

# let's check `FINISH_TOKEN`
input_id = "hello_"
```

not stop, so continue

## Second Iteration
```bash
next_token = "_"
input_id = "hello_"
cache = feature("hello")

# after `self.decode("_")` with **cache**
next_token = 'e'
input_id = 'hello_e'
```
.. continue

until `input_id` has a `FINISH_TOKEN` or `len(input_id) > 2000`.

You can see, there is a `cache` [AKA past_keys and past_values](https://github.com/tpoisonooo/llama.onnx/blob/36a293a38250e859ba10ed5310b7aff237c05fb6/demo-single.py#L40) to record history embed feature.

**Comment by tpoisonooo** [comment]
@yingzhao27

**Comment by yingzhao27** [comment]
Thank you for your reply. I kown what happened. My model is different from yours, and I didn't use the "cache" mechanism. So I must do the above changes, otherwise the result will be very problematic.
