### ISSUE TITLE
Alternative RWKV onnx converter

### ISSUE THREAD

**Issue by harrisonvanderbyl** [tpoisonooo/llama.onnx#17]
Single Graph exporter with wide range of options here: https://github.com/RWKV/rwkv-onnx
Example export options:
![image](https://github.com/tpoisonooo/llama.onnx/assets/33416119/9b835e11-1be3-470c-8c7d-7a297994bb21)

Its a custom tracer and graph builder, so has support for external tensor storage, mixed precision, opslist 17, etc

**Comment by tpoisonooo** [comment]
Good job !
