### ISSUE TITLE
some questions about llama.onnx

### ISSUE THREAD

**Issue by dvc94ch** [tpoisonooo/llama.onnx#3]
1. how did you export the onnx model? I can't see a script in the repo. presumably through `torch.onnx.export`?
2. did you do any optimization on the onnx to reduce it's size? wondering if it can be reduced from 53gb to something a bit more manageable. that's quite big for including into a mobile or desktop app. maybe something like `tract` might be able to reduce the models? [0]

if the size can be reduced to a reasonable amount, I'd be interested in porting your python scripts to `wonnx` to run it on mobile devices.

- [0] https://github.com/sonos/tract
- [1] https://github.com/webonnx/wonnx

**Comment by tpoisonooo** [comment]
1. onnx model exported by `torch.onnx.export`, cherry-pick [this branch]() to `transformers`
2. until now, no optimization on onnx,  but I am still working on it

**Comment by tpoisonooo** [comment]
New model set has been reduced to 26G,  uploading +_+ @dvc94ch

**Comment by dvc94ch** [comment]
tried the 53G model, but I don't have enough memory on my laptop (32g), but with pytorch it did.

**Comment by tpoisonooo** [comment]
OK,  `memory pool` feature is  also on the way.

**Comment by tpoisonooo** [comment]
> what approach[es] are you using to reduce the size? a lot of people have been using 4-bit quantization with https://github.com/qwopqwop200/GPTQ-for-LLaMa my interest in onnx stems mainly from learning about sparsification approaches, not quite sure of the best one
> 
> documenting these things sounds pretty helpful as they impact performance

After `memory pool` feature, I plan to add quantization.

Yes there are many quantization/optimization methods for llama/transformer model
* GPTQ
* llama.cpp
* FQ-ViT
* poolformer structure
* ..

I think the best method must take hardware(instruction and cache for software) into consideration.
So the first question is, **what is your platform**.

**Comment by tpoisonooo** [comment]
> what approach[es] are you using to reduce the size? a lot of people have been using 4-bit quantization with https://github.com/qwopqwop200/GPTQ-for-LLaMa my interest in onnx stems mainly from learning about sparsification approaches, not quite sure of the best one
> 
> documenting these things sounds pretty helpful as they impact performance

Until now (20230411) , I just remove redundant `torch.onnx.export` code and using zero tensor (or empty tensor), 26GB version is not the best.

**Comment by tpoisonooo** [comment]
> interesting, the fp16 files aren't very compressible, only about 8% size reduction.

Try `zip` whole directory,  about `10%`  size reduction.

I guess `zstd` == `zip`.

**Comment by tpoisonooo** [comment]
If `zip -9` onnx fp32 directory, 40% size reduction.
